[package]
name = "tui_monitor"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.36", features = ["full", "tracing"] }
console-subscriber = "0.2"
ratatui = "0.26.1"
crossterm = "0.27"
sysinfo = "0.30"
anyhow = "1.0"
